title: Pilvipalvelut web-kehityksessä
description: Tervetuloa sivustolle!
remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

# VÄRIT
page-col: "#ffffff"
page-img: none
text-col: "#08526d"
link-col: "#138c9f"
hover-col: "#41c2c8"
navbar-col: "#b5e4ee"
navbar-text-col: "#0b556e"
navbar-border-col: "#b5e4ee"
footer-col: "#b5e4ee"
footer-text-col: "#0b556e"
footer-link-col: "#0b556e"
footer-hover-col: "#08526d"

# NAVIGAATIO
navbar-links:
  Etusivu: /
  "Viikko 1": /vko1.html
  "Viikko 2": /vko2.html
  "Viikko 3": ./vko3/index.html
  "Viikko 4": ./vko4/
  "Viikko 5": ./vko5_teksti.html
  "Harjoitustyö": /raportti.html

navbar-fixed: true

round-avatar: true
title-on-all-pages: true
post_search: true

author: Ellinoora Tammi
avatar: /kuva.jpg
social-network-links:
  github: cloudsgoblack
